### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by acopalipsis** [js-data/js-data#294] opened 2016-01-16 19:37 UTC
why the memory leak?

```
import DSHttpAdapter from 'js-data-http';
import {Model, Collection} from 'js-data';

function app(){
    const http = new DSHttpAdapter();
    class Base extends Model {}

    Base.registerAdapter('http', http, {default: true});
    Base.configure({
        basePath: 'http://localhost:3000'
    });

    class User extends Base {
        static endpoint = 'users';
    }

    const UserCollection = new Collection({model: User});

    UserCollection.find(2)
}

setInterval(app, 1000);
```

server side

```
router.get('/:id', function (req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    res.header('Content-Type', 'application/json');
    res.json(new Array(1000000).join('*')/*users[req.params.id]*/);
});
```

If the server is disabled, the memory is immediately cleared.

**Comment by crobinson42** [comment] 2016-01-21 00:16
Do you have some evidence of a memory leak? Screenshots of pm2 monitor etc.?

**Comment by acopalipsis** [comment] 2016-01-21 09:46
![vokoscreen-2016-01-21_12-37-41](https://cloud.githubusercontent.com/assets/9849922/12476836/08f53c54-c03d-11e5-81b1-39a9ada0c600.gif)

**Comment by acopalipsis** [comment] 2016-01-21 09:49
@crobinson42 entry with 1 fps? Longer to write can not, everything is starting to fail, even the cursor stops.

**Comment by crobinson42** [comment] 2016-01-21 16:52
Well, can you replicate the 'memory leak' code with a plunker script or gist link so we can look at cod and replicate on our own machine to help resolve?

**Comment by acopalipsis** [comment] 2016-01-21 17:06
@crobinson42 You said You screenshots will be enough?) And code given in the question itself.

**Comment by crobinson42** [comment] 2016-01-21 17:07
What version of node and packages are you running?

**Comment by jmdobry** [comment] 2016-01-21 17:09
This question may end up being moot because @acopalipsis is using 3.0.0-alpha.x, which is still changing a lot.

**Comment by acopalipsis** [comment] 2016-01-21 17:22
@crobinson42 i use "js-data": "3.0.0-alpha.10" и "js-data-http": "3.0.0-alpha.3". 
add an example on plnkr.co I can't, don't know how to add libraries with the correct versions.
To find the reason I can't either, since my laptop is weak and it freezes before I find something.

**Comment by jmdobry** [comment] 2017-02-20 22:25
Closing as not reproducible. Please comment back here with a JSFiddle, Plunker, or RunKit (Node.js) with which I can reproduce the issue.

**Closed by jmdobry** 2017-02-20 22:25 UTC
Labels: needs more info, v3
