### ISSUE TITLE
Sync between localKey and localField

### ISSUE THREAD

**Issue by guilhermeaiolfi** [js-data/js-data#33] opened 2015-01-16 21:00 UTC
Hi,

I'm evaluating this project and ran into an issue. For example, having this relations:

````javascript
var Status = store.defineResource({
  name: 'status',
  relations: {
    belongsTo: {
      document: {
        localKey: 'document_id',
        localField: 'document'
      }
    }
  }
});
```

if ```status.document_id``` equals ```2``` and I do:

```javascript
Document.find(3).then(function(doc) {
    status.document = doc;
  });
```

The ```status``` record gets in a invalid state regarding ```status.document_id (2)``` and ```status.document(#3)```. 

Am I doing something wrong? Because it seems that it should be the library's responsibility to sync those two related values.

Anyway, great project and I'll probably going to use it. 

Thanks.

**Comment by jmdobry** [comment] 2015-01-16 21:18
Are you saying that (in your example) the status object belongsTo document 2, but in the client-side javascript you're attempting to re-assign the status object to document 3? If so, that would certainly put the data in a broken (unexpected) state. The foreign key field is used to find the relation. If you manually assign the wrong relation, it's not going to change the foreign key to point to the new object–it will be broken.

**Comment by guilhermeaiolfi** [comment] 2015-01-16 21:25
So the right approach would be to change the foreign key ? I wasn't doing
that because I would have to call loadRelations since it seems it's not
done automatically.

But I guess I could ```find``` the right document and change only the
foreign key using ```document.id```. Is that the right way to go?
Em 16/01/2015 19:18, "Jason Dobry" <notifications@github.com> escreveu:

**Comment by jmdobry** [comment] 2015-01-16 21:51
You need to change the foreignKey. However, you may not necessarily have to call loadRelations if the new relation is already in the data store. Example:

```js
var docs = Document.inject([{ id: 2 }, { id: 3 }])

var status = Status.inject({ id: 1, document_id: 2 });

status.document.id; // 2
status.document === docs[0]; // true

status.document_id = 3;

// Re-evaluate relationship links for the status object that has id "1"
Status.link(1, ['document']);

status.document.id; // 3
status.document === docs[1]; // true
```

The above is the expected behavior with default settings.

**Comment by guilhermeaiolfi** [comment] 2015-01-16 22:47
Eventually the relation will be updated without ```Status.link```, right?

```javascript
Document.find(3).then(function(doc) {
    status.document_id = doc.id;
});
...

status.document.id; // 3
```

It seems that it's async, but if I don't need it to be updated right away it's not required to use ```Status.link```.

**Comment by jmdobry** [comment] 2015-01-18 22:23
The `link` function is the only code that can update the link to the document. `link` is called by `inject` if the appropriate options are set to `true`. The only "eventual" way for the link to be updated would be to call `loadRelations`, `link`, or `inject`.

**Comment by jmdobry** [comment] 2015-02-24 17:21
Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.io/org/groupsio/jsdata).

**Closed by jmdobry** 2015-02-24 17:21 UTC
Labels: question
