### ISSUE TITLE
Unable to set endpoint on save method

### ISSUE THREAD

**Issue by risp** [js-data/js-data#166] opened 2015-06-26 12:07 UTC
When I try to save an object using `Object.save(object.id, { endpoint: 'foo' });` then endpoint is ignored it seems. It works when using the find methods, for example `Object.findAll({}, { endpoint: 'foo' })`.

**Comment by jmdobry** [comment] 2015-10-03 17:26
I just added a test for this and it worked. I cannot reproduce the bug.

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [Gitter Channel](https://gitter.im/js-data/js-data) or the [mailing list](https://groups.io/org/groupsio/jsdata).

**Closed by jmdobry** 2015-10-03 17:26 UTC
Labels: bug, needs more info
